#!/usr/bin/env python3
"""Generate sw.js: precache list scanned from the app files, cache version
derived from their content hash. Run from the repo root (CI runs it on every
deploy; run manually only for local preview)."""

import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

SHELL = [
    "./",
    "./index.html",
    "./support.js",
    "./manifest.webmanifest",
    "./icon.webp",
]


def main() -> int:
    refs = set()
    for src in ("index.html", "support.js"):
        refs.update(
            re.findall(r"\./(?:assets|vendor)/[^'\"\s)]+", (ROOT / src).read_text())
        )
    fonts_css = ROOT / "assets" / "fonts" / "fonts.css"
    if fonts_css.exists():
        refs.add("./assets/fonts/fonts.css")
        refs.update(
            "./assets/fonts/" + name.lstrip("./")
            for name in re.findall(r"url\(([^)]+\.woff2)\)", fonts_css.read_text())
        )

    precache = SHELL + sorted(refs)

    missing = [p for p in precache if p != "./" and not (ROOT / p).is_file()]
    if missing:
        print("ERROR: precache entries missing on disk:", *missing, sep="\n  ")
        return 1

    digest = hashlib.sha256()
    for p in precache:
        if p == "./":
            continue
        digest.update(p.encode())
        digest.update((ROOT / p).read_bytes())
    version = digest.hexdigest()[:12]

    entries = ",\n".join("  %s" % json.dumps(p) for p in precache)
    sw = SW_TEMPLATE % {"version": version, "entries": entries}
    (ROOT / "sw.js").write_text(sw)
    print(f"sw.js generated: cache aatif-fitness-{version}, {len(precache)} entries")
    return 0


SW_TEMPLATE = """\
// GENERATED by scripts/generate_sw.py — do not edit by hand.
// Precaches the full app for offline use; the version is a content hash.
const CACHE = 'aatif-fitness-%(version)s';
const PRECACHE = [
%(entries)s
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;

  if (req.mode === 'navigate') {
    // Network-first for the page itself so deploys show up, cache as fallback.
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put('./index.html', copy));
          return res;
        })
        .catch(() => caches.match('./index.html'))
    );
    return;
  }

  // Cache-first for everything else; fill the cache on miss.
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return res;
        })
    )
  );
});
"""

if __name__ == "__main__":
    sys.exit(main())
